---
## from https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml
sudo: required

env:
  - distribution: centos
    version: 8
    init: /usr/lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
  - distribution: ubuntu
    version: 16.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
  - distribution: debian
    version: 8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distribution: debian
    version: 9
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  # - sudo apt-get update
  # Pull container
  - 'docker pull ${distribution}:${version}'
  - env
  - pwd
  - find -ls
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
  - cp test/travis/initctl_faker test/
  # Customize container
  - 'docker build --rm=true --file=test/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible test'

script:
  - container_id=$(mktemp)
    # Run container in detached state
  - 'docker run --detach --volume="${PWD%/*}":/etc/ansible/roles:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm pip --version || true'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm pip3 --version || true'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible --version'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.falco/test/integration/default/default.yml --syntax-check'

  # Test role.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.falco/test/integration/default/default.yml -vvv'

  # Test role idempotence.
  - >
    docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.falco/test/integration/default/default.yml
    | tee /tmp/idempotency.log
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)

after_failure:
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -l /usr/bin/ | egrep "(python|pip|ansible)"'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm pip freeze'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm pip3 freeze'
  # Check what happened on systemd systems.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status falco'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm journalctl -xe --no-pager'

after_script:
  - '[ "X${distribution}" == "Xubuntu" ] && sudo docker exec "$(cat ${container_id})" wget https://packages.chef.io/files/stable/inspec/2.3.4/ubuntu/18.04/inspec_2.3.4-1_amd64.deb || true'
  - '[ "X${distribution}" == "Xubuntu" ] && sudo docker exec "$(cat ${container_id})" dpkg -i inspec_2.3.4-1_amd64.deb || true'
  - '[ "X${distribution}" == "Xcentos" ] && sudo docker exec "$(cat ${container_id})" rpm -Uvh https://packages.chef.io/files/stable/inspec/2.3.4/el/7/inspec-2.3.4-1.el7.x86_64.rpm || true'
  - 'docker exec "$(cat ${container_id})" /opt/inspec/bin/inspec exec https://github.com/juju4/inspec-falco/archive/master.tar.gz'
  # Clean up
  - 'docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
