---
- name: sysdig | setup yum
  include_vars: yum.yml

- name: sysdig | install package key
  rpm_key:
    key: '{{ sysdig_rpm_key }}'
    state: present

- name: sysdig | install repo
  get_url:
    dest: /etc/yum.repos.d/
    url: '{{ sysdig_repo_url }}'

