---
galaxy_info:
  role_name: falco
  author: juju4
  description: Falco, behavioral security with sysdig
  license: BSD
  min_ansible_version: 1.9
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: EL
    versions:
     - 6
     - 7
  - name: Ubuntu
    versions:
    - trusty
    - xenial
    - bionic
  galaxy_tags:
  - system
  - security
  - logging
